spring:
  datasource:
    type: com.mchange.v2.c3p0.ComboPooledDataSource
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    open-in-view: false
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
  cache:
    type: redis
  redis:
    client-name: my-card-redis
    host: localhost
    port: 6380
    timeout: 200
    password: redis-transactions-pwd

server:
  port: 8082

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

security:
  oauth2:
    resource:
      service-id: my-card-auth
      user-info-uri: http://${security.oauth2.resource.service-id}/token
      loadBalanced: true

hystrix:
  shareSecurityContext: true
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 3000
  threadpool:
    default:
      coreSize: 8
      maximumSize: 8

ribbon:
  eager-load:
    enabled: true
    clients: my-card-auth, my-card-cards

logging:
  level:
    org:
      springframework:
        cache: TRACE
    com:
      netflix:
        config:
          sources:
            URLConfigurationSource: ERROR